### PR TITLE
Add matrix enhancements and fixes

### LINKED ISSUE #88: Add Urgency-Importance Matrix as UI Component

### LINKED ISSUE #141: Issues with matrix, unable to open app
- When there is no tasks in json, there will be a NoSuchElement error that prevents app opening.
- When all tasks in json have due date before current date, there will be divided by zero error (split = 0 in MainWindow.java) that prevents app opening.

### PR DESCRIPTION
**Pull request by eyelessrhyme7**
- enhanced and reversed urgency ordering in matrix. 10 is highest urgency and 1 is low. critical element appears in top right cell.
- fixed no such element exception when there's no task.
- fixed delete all error which was showing matrix filled.

closes #88 
closes #141

### CODE REVIEW

**Review by jack1e0 — APPROVED** [review]
lgtm

File: src/main/java/profplan/ui/MainWindow.java [hunk 1]
```diff
@@ -297,25 +297,35 @@ private void loadMatrix() {
...
-        System.out.println(split);
-        System.out.println(minDaysLeft);
-        System.out.println(maxDaysLeft);
-        taskUrgency.replaceAll((t, v) -> v / split + 1);
-
-
-        for (int i = 10; i >= 1; i--) {
-            Order temp = new Order(taskUrgency, String.valueOf(i));
-            rows.add(temp);
+        if (filteredTasks.isEmpty()) {
```
Comment (newway1814) [inline src/main/java/profplan/ui/MainWindow.java:300]: Strictly adhered to code quality nice!

**Review by newway1814 — APPROVED** [review]
LGTM!
